// Test generated by RoostGPT for test knote-java using AI Type Open AI and AI Model gpt-4

package alahyaoui.curriculum.business;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.HashSet;

public class CourseNode_CourseNode_b0239e08bb_Test {

    private CourseNode courseNode;

    @BeforeEach
    public void setUp() {
        courseNode = new CourseNode();
        courseNode.setId("testId");
    }

    @Test
    public void testCourseNodeConstructor_withValidId() {
        assertEquals("testId", courseNode.getId(), "CourseNode id should match the input id");
        assertTrue(courseNode.getPrerequisites().isEmpty(), "Prerequisites set should be initialized and empty");
        assertTrue(courseNode.getCorequisites().isEmpty(), "Corequisites set should be initialized and empty");
    }

    @Test
    public void testCourseNodeConstructor_withNullId() {
        CourseNode nullIdCourseNode = new CourseNode();
        nullIdCourseNode.setId(null);
        assertNull(nullIdCourseNode.getId(), "CourseNode id should be null when input id is null");
        assertTrue(nullIdCourseNode.getPrerequisites().isEmpty(), "Prerequisites set should be initialized and empty");
        assertTrue(nullIdCourseNode.getCorequisites().isEmpty(), "Corequisites set should be initialized and empty");
    }
}
