// Test generated by RoostGPT for test knote-java using AI Type Open AI and AI Model gpt-4

package alahyaoui.curriculum.business;

import java.util.HashMap;
import alahyaoui.curriculum.dto.CourseStateDto;
import alahyaoui.curriculum.model.Course;
import lombok.Value;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Program_Program_331de778eb_Test {

    private Program program;

    @BeforeEach
    public void setup() {
        program = new Program();
    }

    @Test
    public void testProgramConstructor() {
        assertTrue(program.getCoursesToStates() instanceof HashMap);
        assertEquals(0, program.getCoursesToStates().size());
    }

    @Test
    public void testProgramConstructorWithPredefinedMap() {
        HashMap<Course, CourseStateDto> predefinedMap = new HashMap<>();
        predefinedMap.put(new Course(), new CourseStateDto());

        program = new Program();
        program.setCoursesToStates(predefinedMap);

        assertTrue(program.getCoursesToStates() instanceof HashMap);
        assertEquals(1, program.getCoursesToStates().size());
        assertTrue(program.getCoursesToStates().containsKey(new Course()));
        assertEquals(new CourseStateDto(), program.getCoursesToStates().get(new Course()));
    }
}
