INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (1,'CAI1','Communication anglophone contextualisé I','COMMUN',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (1,'CPT1','Comptabilité contextualisée I','COMMUN',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (1,'DEV1','Développement I','COMMUN',10,114);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (1,'INT1','Introduction à l''informatique','COMMUN',10,108);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (1,'MAT1','Mathématique contextualisée','COMMUN',6,72);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'ALG2','Algorithmique II','COMMUN',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'ANA2','Analyse I','COMMUN',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'CAI2','Communication anglophone contextualisée II','COMMUN',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'DEV2','Développement II','COMMUN',6,60);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'DON2','Persistance des données I','COMMUN',5,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'MIC2','Microprocesseurs + laboratoires','COMMUN',3,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'STA2','Statistique contextualisée','COMMUN',3,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'SYS2','Systèmes d''exploitation I','COMMUN',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'ALG3','Algorithmique','COMMUN',4,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'ANA3','Analyse II','COMMUN',4,60);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'DEV3','Développement III','COMMUN',6,72);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'DON3','Persistance des données II','COMMUN',5,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'DEV4','Développement IV','COMMUN',3,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'DON4','Persistance des données III','COMMUN',3,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'VEI5','Veilles technologiques','COMMUN',1,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'WEBG2','Développement Web I','GESTION',5,60);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'ATLG3','Atelier Logiciel I','GESTION',5,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'CAIG3','Communication contextualisée III','GESTION',3,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'DRTG3','Droit et philosophie contextualisés','GESTION',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'ATLG4','Atelier Logiciel II','GESTION',4,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'CPRG4','Complément réseaux','GESTION',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'CPTG4','Comptabilité contextualisée II','GESTION',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'ECOG4','Economie contextualisée','GESTION',3,36);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'ERGG4','Ergonomie du logiciel','GESTION',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'LPDG4','Laboratoire persistance des données III','GESTION',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'SECG4','Sécurité','GESTION',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'SYSG4','Systèmes d''exploitation II','GESTION',5,72);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'WEBG4','Développement Web II','GESTION',3,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'DONG5','Persistance des données IV','GESTION',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'ERPG5','Progiciel de gestion intégré','GESTION',5,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'MOBG5','Développement mobile','GESTION',5,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'ORGG5','Organisation et entreprise','GESTION',3,36);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'PRJG5','Gestion de projet','GESTION',5,72);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'SYSG5','Systèmes d''exploitation III','GESTION',4,36);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'WEBG5','Développement Web III','GESTION',3,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'TEXG5','Expression et communication','GESTION',2,30);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (6,'ETEG6','Epreuve terminale','GESTION',30,350);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'PHYIR2','Physique I','INDUSTRIELLE_RESEAU',3,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (2,'RESIR2','Réseaux I','INDUSTRIELLE_RESEAU',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'SYSIR3','Systèmes d''exploitation II','INDUSTRIELLE_RESEAU',5,72);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'ATLIR4','Atelier Logiciel I','INDUSTRIELLE_RESEAU',5,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'ORGIR5','Organisation des entreprises','INDUSTRIELLE_RESEAU',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'ANLIR5','Laboratoire d''analyse III','INDUSTRIELLE_RESEAU',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'ATLIR5','Atelier Logiciel II','INDUSTRIELLE_RESEAU',4,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'AUTI3','Automates programmables I','INDUSTRIELLE',5,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'AGRI4','Administration et gestion des réseaux','INDUSTRIELLE',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'AVAI4','Acquisition,Visualisation et Analyse','INDUSTRIELLE',5,84);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'EMBI4','Systèmes embarqués','INDUSTRIELLE',5,60);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'IMGI4','Traitement et analyse d''images I','INDUSTRIELLE',1,12);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'IOTI4','Réseaux IOT','INDUSTRIELLE',2,36);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'RLII4','Réseaux Locaux Industriels','INDUSTRIELLE',5,48);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'AUTI5','Automates programmables II','INDUSTRIELLE',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'IEII5','Interfaçage d''équipements industriels','INDUSTRIELLE',2,16);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'IMGI5','Traitement et analyse d''images II','INDUSTRIELLE',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'PIAI5','Projet Intelligence artificielle','INDUSTRIELLE',2,28);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'PRJI5','Projet transversal','INDUSTRIELLE',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'RELI5','Electronique, mécanique et programmation appliquée à la robotique humanoïde','INDUSTRIELLE',3,40);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'ROBI5','Robotique','INDUSTRIELLE',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'SECI5','Eléments de sécurité informatique','INDUSTRIELLE',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'STRI5','Systèmes d''exploitation temps réel','INDUSTRIELLE',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'TEXI5','Expression et communication','INDUSTRIELLE',2,30);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (6,'ETEI6','Epreuve terminale','INDUSTRIELLE',30,350);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'LANR3','Réseaux LAN','RESEAU',5,60);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (3,'PHYR3','Physique II','RESEAU',2,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'AGLR4','Administration et Gestion des Réseaux I','RESEAU',2,36);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'AGWR4','Administration et gestion des réseaux Windows I','RESEAU',2,36);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'RESR4','Réseaux II','RESEAU',1,24);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'WANR4','Réseaux WAN','RESEAU',5,60);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'WIRR4','Réseaux sans fils et mobiles','RESEAU',4,36);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (4,'WEBR4','Développement Web','RESEAU',5,72);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'IXVR5','Réseaux et télécommunication','RESEAU',5,60);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'AGRR5','Administration et sécurité des réseaux II','RESEAU',7,72);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'SECR5','Sécurité','RESEAU',4,36);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'PRJR5','Projet transversal','RESEAU',3,36);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (5,'TEXR5','Expression et communication','RESEAU',2,30);
INSERT INTO courses(quarter,id,title,section,credits,hours) VALUES (6,'ETER6','Epreuve terminale','RESEAU',30,350);