// Test generated by RoostGPT for test knote-java using AI Type Open AI and AI Model gpt-4

package alahyaoui.curriculum.exception;

import alahyaoui.curriculum.model.Section;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

public class SectionNotValidException_SectionNotValidException_f19671db22_Test {

    @Mock
    private Section section;

    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSectionNotValidExceptionWithManagement() {
        when(section.toString()).thenReturn("MANAGEMENT");
        SectionNotValidException exception = new SectionNotValidException(section);
        assertEquals("Section must be either MANAGEMENT, INDUSTRIAL and NETWORK value received: MANAGEMENT", exception.getMessage());
    }

    @Test
    public void testSectionNotValidExceptionWithInvalidSection() {
        when(section.toString()).thenReturn("INVALID");
        SectionNotValidException exception = new SectionNotValidException(section);
        assertEquals("Section must be either MANAGEMENT, INDUSTRIAL and NETWORK value received: INVALID", exception.getMessage());
    }
}
