// Test generated by RoostGPT for test knote-java using AI Type Open AI and AI Model gpt-4

package alahyaoui.curriculum.controller;

import java.util.Arrays;
import java.util.List;
import alahyaoui.curriculum.model.Course;
import alahyaoui.curriculum.model.Section;
import alahyaoui.curriculum.service.CourseService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

public class CourseRestController_getSectionCourses_79b5517948_Test {

    private CourseService courseService;
    private CourseRestController controller;

    @BeforeEach
    public void setUp() {
        courseService = mock(CourseService.class);
        controller = new CourseRestController(courseService);
    }

    @Test
    public void testGetSectionCourses() {
        Section section = new Section();
        Course course1 = new Course();
        Course course2 = new Course();
        List<Course> courses = Arrays.asList(course1, course2);

        when(courseService.getSectionCourses(section)).thenReturn(courses);

        ResponseEntity<List<Course>> response = controller.getSectionCourses(section);

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals(courses, response.getBody());
    }

    @Test
    public void testGetSectionCourses_NoCourses() {
        Section section = new Section();

        when(courseService.getSectionCourses(section)).thenReturn(null);

        ResponseEntity<List<Course>> response = controller.getSectionCourses(section);

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNull(response.getBody());
    }
}
